TkdFront/Pages/Admin/Techniques/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using TkdDTO;
using TkdFront.Services;

namespace TkdFront.Pages.Admin.Techniques
{
    public class EditModel : PageModel
    {
        private readonly IApiClient _apiClient;

        public EditModel(IApiClient apiClient)
        {
            _apiClient = apiClient;
        }

        [BindProperty]
        public Technique Technique { get; set; }


        public async Task OnGetAsync(int id)
        {
            Technique = await _apiClient.GetTechniqueAsync(id);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await _apiClient.PutTechniqueAsync(Technique.Tid, Technique);

            return RedirectToPage();
        }
        public async Task<IActionResult> OnPostDeleteAsync()
        {
            var delete = await _apiClient.GetTechniqueAsync(Technique.Tid);

            if (delete != null)
            {
                await _apiClient.DeleteTechniqueAsync(Technique.Tid);
            }

            return RedirectToPage("/Techniques/Index");
        }
    }
}

TkdFront/Pages/Techniques/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using TkdDTO;
using TkdFront.Services;
using System.Security.Claims;

namespace TkdFront.Pages
{
    public class TechniquesModel : PageModel
    {
        protected readonly IApiClient _apiClient;

        public TechniquesModel(IApiClient apiClient)
        {
            _apiClient = apiClient;
        }

        public List<TechniqueResponse> Techniques { get; set; }
        public List<ImageResponse> Images { get; set; }

        public bool IsAdmin { get; set; }
        public async Task OnGetAsync()
        {
            IsAdmin = User.IsAdmin();
            Techniques = await _apiClient.GetTechniquesAsync();
            Images = await _apiClient.GetImagesAsync();
        }
    }
}

TkdFront/Pages/Techniques/Technique.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using TkdDTO;
using TkdFront.Services;
using System.Security.Claims;

namespace TkdFront.Pages
{
    public class TechniqueModel : PageModel
    {
        protected readonly IApiClient _apiClient;

        public TechniqueModel(IApiClient apiClient)
        {
            _apiClient = apiClient;
        }

        public TechniqueResponse Technique { get; set; }
        public List<ImageResponse> Images { get; set; }

        public bool IsAdmin { get; set; }
        public async Task OnGetAsync(int id)
        {
            IsAdmin = User.IsAdmin();
            Technique = await _apiClient.GetTechniqueAsync(id);
            Images = await _apiClient.GetImagesAsync(Technique.Wid);
        }
    }
}

TkdFront/Pages/Admin/Techniques/Edit.cshtml
@page "{id}"
@model TkdFront.Pages.Admin.Techniques.EditModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Technique @Model.Technique.Tid</h1>

<div>
    <form method="post" class="form-horizontal">
        <div asp-validation-summary="All" class="text-danger" />
        <input asp-for="@Model.Technique.Tid" type="hidden" />
        <input asp-for="@Model.Technique.Wid" type="hidden" />
        <input asp-for="@Model.Technique.Lcode" type="hidden" />

        <div class="form-group">
            <label for="Technique.Tdescription">Description</label>
            <input asp-for="@Model.Technique.Tdescription" class="form-control" />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary">Save</button>
                <button type="submit" asp-page-handler="Delete" class="btn btn-danger">Delete</button>
            </div>
        </div>
    </form>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}