TkdFront/Pages/Admin/Panel/CreationPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using TkdDTO;
using TkdFront.Services;

namespace TkdFront.Pages.Admin
{
    public class CreationPageModel : PageModel
    {

        private readonly IApiClient _apiClient;

        public CreationPageModel(IApiClient apiClient)
        {
            _apiClient = apiClient;
        }

        [BindProperty]
        public Word Word { get; set; }

        [BindProperty]
        public Technique Technique { get; set; }

        [BindProperty]
        public Language Language { get; set; }

        [BindProperty]
        public Image Image { get; set; }

        public async Task<IActionResult> OnPostWordAsync()
        {
            var response = await _apiClient.PostWordAsync(Word);
            //return RedirectToPage($"EditWord", new { id = Word.Wid });
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostTechniueAsync()
        {
            var response = await _apiClient.PostTechniqueAsync(Technique);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostLanguageAsync()
        {
            var response = await _apiClient.PostLanguageAsync(Language);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostImageAsync()
        {
            var response = await _apiClient.PostImageAsync(Image);

            return RedirectToPage();
        }
    }
}

TkdFront/Pages/Admin/Panel/CreationPage.cshtml
@page
@model CreationPageModel
@{
}
<p>
    <button class="btn btn-primary" data-toggle="collapse" data-target="#addWord" type="button" aria-expanded="false" aria-controls="addWord">
        Add Word
    </button>
    <button class="btn btn-primary" data-toggle="collapse" data-target="#addTechnique" type="button" aria-expanded="false" aria-controls="addTechnique">
        Add Technique
    </button>
    <button class="btn btn-primary" data-toggle="collapse" data-target="#addLanguage" type="button" aria-expanded="false" aria-controls="addLanguage">
        Add Language
    </button>
    <button class="btn btn-primary" data-toggle="collapse" data-target="#addImage" type="button" aria-expanded="false" aria-controls="addImage">
        Add Image
    </button>
</p>

<div class="collapse" id="addWord">
    <form asp-page-handler="Word" method="post" class="form-horizontal">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label for="Wid">Wid:</label>
            <input type="text" class="form-control" name="Word.Wid">
            <label for="Lcode">Lcode:</label>
            <input type="text" class="form-control" name="Word.Lcode">
            <label for="Wterm">Wterm:</label>
            <input type="text" class="form-control" name="Word.Wterm">
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit"  asp-page-handler="Word" class="btn btn-primary">Save</button>
                <button type="reset" class="btn btn-danger">Reset Form</button>
            </div>
        </div>
    </form>
</div>
<div class="collapse" id="addTechnique">
    <form asp-page-handler="Technique" method="post" class="form-horizontal">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label for="Tid">Tid:</label>
            <input type="text" class="form-control" name="Technique.Tid">
            <label for="Wid">Wid:</label>
            <input type="text" class="form-control" name="Technique.Wid">
            <label for="Lcode">Lcode:</label>
            <input type="text" class="form-control" name="Technique.Lcode">
            <label for="Tdescription">Tdescription:</label>
            <input type="text" class="form-control" name="Technique.Tdescription">
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" asp-page-handler="Technique" class="btn btn-primary">Save</button>
                <button type="reset" class="btn btn-danger">Reset Form</button>
            </div>
        </div>
    </form>
</div>

<div class="collapse" id="addImage">
    <form asp-page-handler="Image" method="post" class="form-horizontal">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label for="Image.Iid">Image id</label>
            <input type="text" class="form-control" name="Image.Iid">
            <label for="Image.Wid">Word Id</label>
            <input type="text" class="form-control" name="Image.Wid">
            <label for="Image.Lcode">Lcode</label>
            <input type="text" class="form-control" name="Image.Lcode">
            <label for="Image.Order">Order</label>
            <input type="text" class="form-control" name="Image.Order">
            <label for="Image.Link">Link</label>
            <input type="text" class="form-control" name="Image.Link">
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" asp-page-handler="Image" class="btn btn-primary">Save</button>
                <button type="reset" class="btn btn-danger">Reset Form</button>
            </div>
        </div>
    </form>
</div>

<div class="collapse" id="addLanguage">
    <form asp-page-handler="Language" method="post" class="form-horizontal">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label for="Language.Lcode">Lcode:</label>
            <input type="text" class="form-control" name="Language.Lcode">
            <label for="Language.Name">Name:</label>
            <input type="text" class="form-control" name="Language.Name">
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" asp-page-handler="Language" class="btn btn-primary">Save</button>
                <button type="reset"  class="btn btn-danger">Reset Form</button>
            </div>
        </div>
    </form>
</div>